// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package greeter

import (
	"context"
	"io"
)

// Injectors from wire.go:

func InitializeGreeter(ctx context.Context, msg []Message, w io.Writer, r io.Reader) (*Greeter, error) {
	options := &Options{
		Message: msg,
		Writer:  w,
		Reader:  r,
	}
	greeter, err := NewGreeter(ctx, options)
	if err != nil {
		return nil, err
	}
	return greeter, nil
}
