// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package injector

import (
	"github.com/vicren/wire-sample/returnfunc/user"
)

// Injectors from wire.go:

func InitializeUser(name string) (*user.Repo, func(), error) {
	repo, cleanup, err := user.NewRepo(name)
	if err != nil {
		return nil, nil, err
	}
	return repo, func() {
		cleanup()
	}, nil
}
