// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package injector

import (
	"github.com/vicren/wire-sample/returnerror/user"
)

// Injectors from injector.go:

func InitializeUser(name string) (*user.User, error) {
	userUser, err := user.NewUser(name)
	if err != nil {
		return nil, err
	}
	return userUser, nil
}
