// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package injector

import (
	"github.com/vicren/wire-sample/interface/user"
)

// Injectors from wire.go:

func InitializeUserService(foo string, bar int) *user.UserService {
	mockUserRepo := user.NewMockUserRepo(foo, bar)
	userService := user.NewUserService(mockUserRepo)
	return userService
}
